name: Build Unsigned IPA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies (CocoaPods)
        run: |
          if [ -f "Podfile" ]; then
            pod install
          fi

      - name: Build App
        run: |
          # Bash uses 'fi' to close an 'if' block
          if [ -d "maciOS.xcworkspace" ]; then
            FILE_FLAG="-workspace maciOS.xcworkspace"
          else
            FILE_FLAG="-project maciOS.xcodeproj"
          fi

          xcodebuild clean build \
            $FILE_FLAG \
            -scheme "maciOS" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            -derivedDataPath build

      - name: Package IPA
        run: |
          mkdir Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r maciOS.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-maciOS-IPA
          path: maciOS.ipa
